name: Tests

on:
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5.1.0
        with:
          version: latest
          args: --timeout 30m

  test:
    name: Run Tests
    needs: golangci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - name: run tests
        env:
          TEST_ACC: "1"
          B2C_ARM_TENANT_ID: ${{ secrets.B2C_ARM_TENANT_ID }}
          B2C_ARM_CLIENT_ID: ${{ secrets.B2C_ARM_CLIENT_ID }}
          B2C_ARM_CLIENT_SECRET: ${{ secrets.B2C_ARM_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.B2C_ARM_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.B2C_ARM_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.B2C_ARM_CLIENT_SECRET }}
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
      - uses: tj-actions/coverage-badge-go@v2.4.2
        with:
          filename: coverage.out
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update coverage badge"
          file_pattern: README.md