name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: latest

  test:
    name: Run Tests
    needs: golangci
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - env:
          TEST_ACC: "1"
          B2C_ARM_TENANT_ID: ${{ secrets.B2C_ARM_TENANT_ID }}
          B2C_ARM_CLIENT_ID: ${{ secrets.B2C_ARM_CLIENT_ID }}
          B2C_ARM_CLIENT_SECRET: ${{ secrets.B2C_ARM_CLIENT_SECRET }}
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v2.4.2
        with:
          filename: coverage.out